export const coursesData = {
  title: "Todos os cursos",
  breadcrumb: [{ label: "Página inicial", href: "/" }],
  courseformats: [
    { id: 1111, label: "Presencial" },
    { id: 2222, label: "Virtual" },
    { id: 3333, label: "Simpósio" },
  ],
  knowledgeAreas: [
    { id: 1231, label: "Emfermagem" },
    { id: 2421, label: "Medicina" },
    { id: 3223, label: "Família" },
    { id: 4332, label: "Desenvolvimento pessoal e profissional" },
    { id: 5444, label: "Empreendedorismo" },
  ],
  coursesList: [
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    },
    {
      title: "Cuidados com o recém nascido",
      courseformat: 1111,
      imageUrl: "/course-image.png",
      description:
        "Na emocionante jornada do nascimento, a confiança e preparação são essenciais para uma rotina tranquila e segura.",
      price: "R$ 799,00",
      date: "18 de Junho",
      hour: "14:00",
      link: "/courses/cuidados-com-o-recem-nascido",
      knowledgeAreas: [1231, 2421],
    }
  ],
};
