export const courseData = {
  title: "Cuidados com o recém nascido",
  breadcrumb: [
    { label: "Página inicial", href: "/" },
    { label: "Todos os cursos", href: "/cursos" },
  ],
  banner: {
    src: "/course-image.png",
    alt: "Descrição do Banner",
  },
  navContent: [
    {
      title: "Sobre o curso",
      content:
        "<p>Na jornada emocionante que se inicia com o nascimento de um bebê, cada momento é único e precioso. É nesse turbilhão de sentimentos que a confiança e a preparação para cuidar e proteger se tornam essenciais, estabelecendo a base para uma rotina mais tranquila e segura.</p><p>O nosso curso presencial Cuidados com o recém-nascido foi projetado para oferecer às gestantes, famílias e redes de apoio as habilidades e o conhecimento necessários para garantir o bem-estar do bebê e criar uma conexão emocional forte desde os primeiros dias de vida desse novo ser.</p><p>Ministrado por uma enfermeira especializada do Grupo Fleury, você e um acompanhante terão 4 horas de aprendizado e prática sobre os principais tópicos e dúvidas que podem surgir ao cuidar do seu bebê. Além de conhecimento, vocês receberão todo o acolhimento que precisam, saindo do nosso encontro com confiança para encarar os desafios dessa fase tão especial.</p><p>O curso abordará temas fundamentais, desde os cuidados de higiene do bebê em casa até dicas vitais sobre arroto, regurgitação e soluço. Você também aprenderá técnicas eficazes para acalmar o bebê, receberá orientações valiosas sobre a amamentação, os primeiros socorros e a segurança, entre outros assuntos essenciais que garantem uma experiência mais leve para todos.</p><p>Com quase um século de expertise no cuidado com a saúde, queremos guiá-los nessa viagem de descoberta e prepará-los para receber o novo membro da família com todo o amor e cuidado que ele merece.</p><ul><li>Instrutores especializados e experientes no cuidado com recém-nascidos;</li><li>Duas pessoas por inscrição;</li><li>Curso presencial e prático, com experiências realistas;</li><li>Conteúdo abrangente e atualizado, baseado em evidências científicas e práticas humanizadas;</li><li>Material de apoio on-line, com videoaulas e simulações;</li><li>12 meses de acesso ao curso a partir da inscrição.</li></ul>",
    },
    {
      title: "Programação",
      content:
        "<p>Na jornada emocionante que se inicia com o nascimento de um bebê, cada momento é único e precioso. É nesse turbilhão de sentimentos que a confiança e a preparação para cuidar e proteger se tornam essenciais, estabelecendo a base para uma rotina mais tranquila e segura.</p><p>O nosso curso presencial Cuidados com o recém-nascido foi projetado para oferecer às gestantes, famílias e redes de apoio as habilidades e o conhecimento necessários para garantir o bem-estar do bebê e criar uma conexão emocional forte desde os primeiros dias de vida desse novo ser.</p><p>Ministrado por uma enfermeira especializada do Grupo Fleury, você e um acompanhante terão 4 horas de aprendizado e prática sobre os principais tópicos e dúvidas que podem surgir ao cuidar do seu bebê. Além de conhecimento, vocês receberão todo o acolhimento que precisam, saindo do nosso encontro com confiança para encarar os desafios dessa fase tão especial.</p><p>O curso abordará temas fundamentais, desde os cuidados de higiene do bebê em casa até dicas vitais sobre arroto, regurgitação e soluço. Você também aprenderá técnicas eficazes para acalmar o bebê, receberá orientações valiosas sobre a amamentação, os primeiros socorros e a segurança, entre outros assuntos essenciais que garantem uma experiência mais leve para todos.</p><p>Com quase um século de expertise no cuidado com a saúde, queremos guiá-los nessa viagem de descoberta e prepará-los para receber o novo membro da família com todo o amor e cuidado que ele merece.</p><ul><li>Instrutores especializados e experientes no cuidado com recém-nascidos;</li><li>Duas pessoas por inscrição;</li><li>Curso presencial e prático, com experiências realistas;</li><li>Conteúdo abrangente e atualizado, baseado em evidências científicas e práticas humanizadas;</li><li>Material de apoio on-line, com videoaulas e simulações;</li><li>12 meses de acesso ao curso a partir da inscrição.</li></ul>",
    },
    {
      title: "Público-Alvo",
      content:
        "<p>Na jornada emocionante que se inicia com o nascimento de um bebê, cada momento é único e precioso. É nesse turbilhão de sentimentos que a confiança e a preparação para cuidar e proteger se tornam essenciais, estabelecendo a base para uma rotina mais tranquila e segura.</p><p>O nosso curso presencial Cuidados com o recém-nascido foi projetado para oferecer às gestantes, famílias e redes de apoio as habilidades e o conhecimento necessários para garantir o bem-estar do bebê e criar uma conexão emocional forte desde os primeiros dias de vida desse novo ser.</p><p>Ministrado por uma enfermeira especializada do Grupo Fleury, você e um acompanhante terão 4 horas de aprendizado e prática sobre os principais tópicos e dúvidas que podem surgir ao cuidar do seu bebê. Além de conhecimento, vocês receberão todo o acolhimento que precisam, saindo do nosso encontro com confiança para encarar os desafios dessa fase tão especial.</p><p>O curso abordará temas fundamentais, desde os cuidados de higiene do bebê em casa até dicas vitais sobre arroto, regurgitação e soluço. Você também aprenderá técnicas eficazes para acalmar o bebê, receberá orientações valiosas sobre a amamentação, os primeiros socorros e a segurança, entre outros assuntos essenciais que garantem uma experiência mais leve para todos.</p><p>Com quase um século de expertise no cuidado com a saúde, queremos guiá-los nessa viagem de descoberta e prepará-los para receber o novo membro da família com todo o amor e cuidado que ele merece.</p><ul><li>Instrutores especializados e experientes no cuidado com recém-nascidos;</li><li>Duas pessoas por inscrição;</li><li>Curso presencial e prático, com experiências realistas;</li><li>Conteúdo abrangente e atualizado, baseado em evidências científicas e práticas humanizadas;</li><li>Material de apoio on-line, com videoaulas e simulações;</li><li>12 meses de acesso ao curso a partir da inscrição.</li></ul>",
    },
    {
      title: "Objetivos",
      content:
        "<p>Na jornada emocionante que se inicia com o nascimento de um bebê, cada momento é único e precioso. É nesse turbilhão de sentimentos que a confiança e a preparação para cuidar e proteger se tornam essenciais, estabelecendo a base para uma rotina mais tranquila e segura.</p><p>O nosso curso presencial Cuidados com o recém-nascido foi projetado para oferecer às gestantes, famílias e redes de apoio as habilidades e o conhecimento necessários para garantir o bem-estar do bebê e criar uma conexão emocional forte desde os primeiros dias de vida desse novo ser.</p><p>Ministrado por uma enfermeira especializada do Grupo Fleury, você e um acompanhante terão 4 horas de aprendizado e prática sobre os principais tópicos e dúvidas que podem surgir ao cuidar do seu bebê. Além de conhecimento, vocês receberão todo o acolhimento que precisam, saindo do nosso encontro com confiança para encarar os desafios dessa fase tão especial.</p><p>O curso abordará temas fundamentais, desde os cuidados de higiene do bebê em casa até dicas vitais sobre arroto, regurgitação e soluço. Você também aprenderá técnicas eficazes para acalmar o bebê, receberá orientações valiosas sobre a amamentação, os primeiros socorros e a segurança, entre outros assuntos essenciais que garantem uma experiência mais leve para todos.</p><p>Com quase um século de expertise no cuidado com a saúde, queremos guiá-los nessa viagem de descoberta e prepará-los para receber o novo membro da família com todo o amor e cuidado que ele merece.</p><ul><li>Instrutores especializados e experientes no cuidado com recém-nascidos;</li><li>Duas pessoas por inscrição;</li><li>Curso presencial e prático, com experiências realistas;</li><li>Conteúdo abrangente e atualizado, baseado em evidências científicas e práticas humanizadas;</li><li>Material de apoio on-line, com videoaulas e simulações;</li><li>12 meses de acesso ao curso a partir da inscrição.</li></ul>",
    },
    {
      title: "Metodologia",
      content:
        "<p>Na jornada emocionante que se inicia com o nascimento de um bebê, cada momento é único e precioso. É nesse turbilhão de sentimentos que a confiança e a preparação para cuidar e proteger se tornam essenciais, estabelecendo a base para uma rotina mais tranquila e segura.</p><p>O nosso curso presencial Cuidados com o recém-nascido foi projetado para oferecer às gestantes, famílias e redes de apoio as habilidades e o conhecimento necessários para garantir o bem-estar do bebê e criar uma conexão emocional forte desde os primeiros dias de vida desse novo ser.</p><p>Ministrado por uma enfermeira especializada do Grupo Fleury, você e um acompanhante terão 4 horas de aprendizado e prática sobre os principais tópicos e dúvidas que podem surgir ao cuidar do seu bebê. Além de conhecimento, vocês receberão todo o acolhimento que precisam, saindo do nosso encontro com confiança para encarar os desafios dessa fase tão especial.</p><p>O curso abordará temas fundamentais, desde os cuidados de higiene do bebê em casa até dicas vitais sobre arroto, regurgitação e soluço. Você também aprenderá técnicas eficazes para acalmar o bebê, receberá orientações valiosas sobre a amamentação, os primeiros socorros e a segurança, entre outros assuntos essenciais que garantem uma experiência mais leve para todos.</p><p>Com quase um século de expertise no cuidado com a saúde, queremos guiá-los nessa viagem de descoberta e prepará-los para receber o novo membro da família com todo o amor e cuidado que ele merece.</p><ul><li>Instrutores especializados e experientes no cuidado com recém-nascidos;</li><li>Duas pessoas por inscrição;</li><li>Curso presencial e prático, com experiências realistas;</li><li>Conteúdo abrangente e atualizado, baseado em evidências científicas e práticas humanizadas;</li><li>Material de apoio on-line, com videoaulas e simulações;</li><li>12 meses de acesso ao curso a partir da inscrição.</li></ul>",
    },
    {
      title: "Investimento",
      content:
        "<p>Na jornada emocionante que se inicia com o nascimento de um bebê, cada momento é único e precioso. É nesse turbilhão de sentimentos que a confiança e a preparação para cuidar e proteger se tornam essenciais, estabelecendo a base para uma rotina mais tranquila e segura.</p><p>O nosso curso presencial Cuidados com o recém-nascido foi projetado para oferecer às gestantes, famílias e redes de apoio as habilidades e o conhecimento necessários para garantir o bem-estar do bebê e criar uma conexão emocional forte desde os primeiros dias de vida desse novo ser.</p><p>Ministrado por uma enfermeira especializada do Grupo Fleury, você e um acompanhante terão 4 horas de aprendizado e prática sobre os principais tópicos e dúvidas que podem surgir ao cuidar do seu bebê. Além de conhecimento, vocês receberão todo o acolhimento que precisam, saindo do nosso encontro com confiança para encarar os desafios dessa fase tão especial.</p><p>O curso abordará temas fundamentais, desde os cuidados de higiene do bebê em casa até dicas vitais sobre arroto, regurgitação e soluço. Você também aprenderá técnicas eficazes para acalmar o bebê, receberá orientações valiosas sobre a amamentação, os primeiros socorros e a segurança, entre outros assuntos essenciais que garantem uma experiência mais leve para todos.</p><p>Com quase um século de expertise no cuidado com a saúde, queremos guiá-los nessa viagem de descoberta e prepará-los para receber o novo membro da família com todo o amor e cuidado que ele merece.</p><ul><li>Instrutores especializados e experientes no cuidado com recém-nascidos;</li><li>Duas pessoas por inscrição;</li><li>Curso presencial e prático, com experiências realistas;</li><li>Conteúdo abrangente e atualizado, baseado em evidências científicas e práticas humanizadas;</li><li>Material de apoio on-line, com videoaulas e simulações;</li><li>12 meses de acesso ao curso a partir da inscrição.</li></ul>",
    },
    {
      title: "Local e horário",
      content:
        "<p>Na jornada emocionante que se inicia com o nascimento de um bebê, cada momento é único e precioso. É nesse turbilhão de sentimentos que a confiança e a preparação para cuidar e proteger se tornam essenciais, estabelecendo a base para uma rotina mais tranquila e segura.</p><p>O nosso curso presencial Cuidados com o recém-nascido foi projetado para oferecer às gestantes, famílias e redes de apoio as habilidades e o conhecimento necessários para garantir o bem-estar do bebê e criar uma conexão emocional forte desde os primeiros dias de vida desse novo ser.</p><p>Ministrado por uma enfermeira especializada do Grupo Fleury, você e um acompanhante terão 4 horas de aprendizado e prática sobre os principais tópicos e dúvidas que podem surgir ao cuidar do seu bebê. Além de conhecimento, vocês receberão todo o acolhimento que precisam, saindo do nosso encontro com confiança para encarar os desafios dessa fase tão especial.</p><p>O curso abordará temas fundamentais, desde os cuidados de higiene do bebê em casa até dicas vitais sobre arroto, regurgitação e soluço. Você também aprenderá técnicas eficazes para acalmar o bebê, receberá orientações valiosas sobre a amamentação, os primeiros socorros e a segurança, entre outros assuntos essenciais que garantem uma experiência mais leve para todos.</p><p>Com quase um século de expertise no cuidado com a saúde, queremos guiá-los nessa viagem de descoberta e prepará-los para receber o novo membro da família com todo o amor e cuidado que ele merece.</p><ul><li>Instrutores especializados e experientes no cuidado com recém-nascidos;</li><li>Duas pessoas por inscrição;</li><li>Curso presencial e prático, com experiências realistas;</li><li>Conteúdo abrangente e atualizado, baseado em evidências científicas e práticas humanizadas;</li><li>Material de apoio on-line, com videoaulas e simulações;</li><li>12 meses de acesso ao curso a partir da inscrição.</li></ul>",
    },
  ],
  courseDetails: {
    title: "Curso Cuidados com o recém nascido",
    workload: "4 horas",
    modality: "Online",
    methodology: "Ensino",
    area: "Medicina",
    addressMap: { lat: -5.082451144954682, lng: -37.61637601889755 },
    investment: "R$ 799,00 (em até 10 x de 79,90)",
    link: "https://cursos.ensinofleury.com.br/turma/cuidados-com-o-recem-nascido/presencial-4",
  },
  video: {
    src: "/video/recém-nascido.mp4",
    thumb: "/course-image.png",
  },
};
